"""new fields in user model

Revision ID: 153aeea13050
Revises: acff09e9f09c
Create Date: 2021-11-27 17:27:07.905364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153aeea13050'
down_revision = 'acff09e9f09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('info', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'info')
    # ### end Alembic commands ###
